# 6.2 Binary Data Format

In [1]:
import os
import sys

# 设置项目根目录（根据你的实际路径调整）
PROJECT_ROOT = '/mnt/d/quant_projects'
os.chdir(PROJECT_ROOT)
print(f"工作目录已切换到: {os.getcwd()}")

工作目录已切换到: /mnt/d/quant_projects

In [2]:
import pandas as pd

In [3]:
frame = pd.read_csv('pydata-book/examples/ex1.csv')

In [4]:
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
frame.to_pickle('pydata-book/examples/frame_pickle')

In [6]:
pd.read_pickle('pydata-book/examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

## 6.2.1 Reading Microsoft Excel Files

In [7]:
conda install openpyxl xlrd

2 channel Terms of Service accepted
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/shaoyu-xu/miniconda3/envs/quant

  added / updated specs:
    - openpyxl
    - xlrd


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2026.7.16  |       h06a4308_0         106 KB
    et_xmlfile-2.0.0           |  py311h06a4308_0          34 KB
    openpyxl-3.1.5             |  py311h5eee18b_1         733 KB
    xlrd-2.0.2                 |     pyhd3eb1b0_0          91 KB
    ------------------------------------------------------------
                                           Total:         964 KB

The following NEW packages will be INSTALLED:

  et_xmlfile         pkgs/main/linux-64::et_xmlfile-2.0.0-py311h06a4308_0
  openpyxl           pkgs/main/linux-64::openpyxl-3.1.5-py311h5eee18b_1
  xlrd               pkgs/main/noarch::xlrd-2.0.2-pyhd3eb1b0_0

The following packages will be UPDATED:

  ca-certificates                      2026.5.14-h06a4308_0 --> 2026.7.16-h06a4308_0



Downloading and Extracting Packages:
openpyxl-3.1.5       | 733 KB    |                                      |   0%
ca-certificates-2026 | 106 KB    |                                      |   0%

xlrd-2.0.2           | 91 KB     |                                      |   0%


openpyxl-3.1.5       | 733 KB    | 7                                    |   2%
ca-certificates-2026 | 106 KB    | #####4                               |  15%

xlrd-2.0.2           | 91 KB     | ######3                              |  18%


et_xmlfile-2.0.0     | 34 KB     | ################9                    |  47%


et_xmlfile-2.0.0     | 34 KB     | #################################### | 100%


openpyxl-3.1.5       | 733 KB    | ###9                                 |  11%

xlrd-2.0.2           | 91 KB     | ###############################7     |  88%
ca-certificates-2026 | 106 KB    | ###########################1         |  75%

xlrd-2.0.2           | 91 KB     | #################################### | 100%
ca-certificates-2026 | 106 KB    | #################################### | 100%

openpyxl-3.1.5       | 733 KB    | ########6                            |  24%







Preparing transaction: done
Verifying transaction: done
Executing transaction: done
WARNING conda.conda_pypi.main:notify_externally_managed_future(156):
  Did you know? You can install many PyPI packages with conda
  using the conda-pypi beta. Get started:
    https://docs.conda.io/projects/conda/en/stable/new-features.html


Note: you may need to restart the kernel to use updated packages.

In [8]:
xlsx = pd.ExcelFile('pydata-book/examples/ex1.xlsx')

In [9]:
xlsx.sheet_names

['Sheet1']

In [10]:
xlsx.parse(sheet_name='Sheet1')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [11]:
xlsx.parse(sheet_name='Sheet1', index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [12]:
frame = pd.read_excel('pydata-book/examples/ex1.xlsx', sheet_name='Sheet1')

In [13]:
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [14]:
writer = pd.ExcelWriter('pydata-book/examples/ex2.xlsx')

In [17]:
frame.to_excel(writer, sheet_name='Sheet1')

In [18]:
writer.save()

AttributeError: 'OpenpyxlWriter' object has no attribute 'save'

In [19]:
frame.to_excel('pydata-book/examples/ex2.xlsx')