# 6.2 Binary Data Format

In [1]:
import os
import sys

# 设置项目根目录（根据你的实际路径调整）
PROJECT_ROOT = '/mnt/d/quant_projects'
os.chdir(PROJECT_ROOT)
print(f"工作目录已切换到: {os.getcwd()}")

工作目录已切换到: /mnt/d/quant_projects

In [2]:
import pandas as pd
import numpy as np

In [3]:
frame = pd.read_csv('pydata-book/examples/ex1.csv')

In [4]:
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
frame.to_pickle('pydata-book/examples/frame_pickle')

In [6]:
pd.read_pickle('pydata-book/examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

## 6.2.1 Reading Microsoft Excel Files

In [7]:
conda install openpyxl xlrd

2 channel Terms of Service accepted
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

WARNING conda.conda_pypi.main:notify_externally_managed_future(156):
  Did you know? You can install many PyPI packages with conda
  using the conda-pypi beta. Get started:
    https://docs.conda.io/projects/conda/en/stable/new-features.html


Note: you may need to restart the kernel to use updated packages.

In [8]:
xlsx = pd.ExcelFile('pydata-book/examples/ex1.xlsx')

In [9]:
xlsx.sheet_names

['Sheet1']

In [10]:
xlsx.parse(sheet_name='Sheet1')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [11]:
xlsx.parse(sheet_name='Sheet1', index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [12]:
frame = pd.read_excel('pydata-book/examples/ex1.xlsx', sheet_name='Sheet1')

In [13]:
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [14]:
writer = pd.ExcelWriter('pydata-book/examples/ex2.xlsx')

In [15]:
frame.to_excel(writer, sheet_name='Sheet1')

In [16]:
writer.save()

AttributeError: 'OpenpyxlWriter' object has no attribute 'save'

In [ ]:
frame.to_excel('pydata-book/examples/ex2.xlsx')

## 6.2.2 Using the HDF5 format

In [ ]:
conda install pytables

2 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/shaoyu-xu/miniconda3/envs/quant

  added / updated specs:
    - pytables


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aws-c-auth-0.10.1          |       h47b2149_0         118 KB
    aws-c-cal-0.9.13           |       h1b28b03_0          53 KB
    aws-c-common-0.12.6        |       h47b2149_0         233 KB
    aws-c-compression-0.3.2    |       h47b2149_0          18 KB
    aws-c-http-0.10.13         |       h47b2149_0         199 KB
    aws-c-io-0.26.3            |       h1b29dbc_0         161 KB
    aws-c-s3-0.12.0            |       h1b28b03_1         132 KB
    aws-c-sdkutils-0.2.4       |       h47b2149_2          54 KB
    aws-checksums-0.2.10       |       h47b2149_0          95 KB
    blas-1.0                   |              mkl           6 KB
    blosc-1.21.6               |       hf7d4471_0          60 KB
    c-blosc2-2.22.0            |       h320d3c0_0         701 KB
    hdf5-2.0.0                 |       h91801a2_3         7.2 MB
    intel-openmp-2025.0.0      |    h06a4308_1172        19.3 MB
    libcurl-8.21.0             |       hd8fa685_0         501 KB
    libgfortran-15.2.0         |       h166f726_8          28 KB
    libgfortran5-15.2.0        |       hc633d37_8         1.5 MB
    lmdb-1.0.0                 |       hfe55579_0         518 KB
    lzo-2.10                   |       h7b6447c_2         184 KB
    mkl-2025.0.0               |     h6d8faa4_942       113.4 MB
    mkl-service-2.7.2          |  py311h365c7f6_0          75 KB
    mkl_fft-2.2.0              |  py311h44c8d7b_0         182 KB
    mkl_random-1.4.1           |  py311h86c3e14_0         393 KB
    numexpr-2.14.1             |  py311hf74ea54_1         212 KB
    numpy-2.4.6                |  py311h4c24699_0          20 KB
    numpy-base-2.4.6           |  py311h00548fb_0         8.6 MB
    py-cpuinfo-9.0.0           |  py311h06a4308_0          64 KB
    pytables-3.11.1            |  py311h4db2897_0         1.5 MB
    s2n-1.6.2                  |       h02aa81b_0         385 KB
    tbb-2022.0.0               |       hdb19cb5_0         188 KB
    tbb-devel-2022.0.0         |       hdb19cb5_0         1.1 MB
    zlib-ng-2.0.7              |       h5eee18b_0         100 KB
    ------------------------------------------------------------
                                           Total:       157.2 MB

The following NEW packages will be INSTALLED:

  aws-c-auth         pkgs/main/linux-64::aws-c-auth-0.10.1-h47b2149_0
  aws-c-cal          pkgs/main/linux-64::aws-c-cal-0.9.13-h1b28b03_0
  aws-c-common       pkgs/main/linux-64::aws-c-common-0.12.6-h47b2149_0
  aws-c-compression  pkgs/main/linux-64::aws-c-compression-0.3.2-h47b2149_0
  aws-c-http         pkgs/main/linux-64::aws-c-http-0.10.13-h47b2149_0
  aws-c-io           pkgs/main/linux-64::aws-c-io-0.26.3-h1b29dbc_0
  aws-c-s3           pkgs/main/linux-64::aws-c-s3-0.12.0-h1b28b03_1
  aws-c-sdkutils     pkgs/main/linux-64::aws-c-sdkutils-0.2.4-h47b2149_2
  aws-checksums      pkgs/main/linux-64::aws-checksums-0.2.10-h47b2149_0
  blas               pkgs/main/linux-64::blas-1.0-mkl
  blosc              pkgs/main/linux-64::blosc-1.21.6-hf7d4471_0
  c-ares             pkgs/main/linux-64::c-ares-1.34.7-hd44998d_0
  c-blosc2           pkgs/main/linux-64::c-blosc2-2.22.0-h320d3c0_0
  gettext            pkgs/main/linux-64::gettext-0.25.1-h92eb808_0
  gettext-tools      pkgs/main/linux-64::gettext-tools-0.25.1-h6a67909_0
  hdf5               pkgs/main/linux-64::hdf5-2.0.0-h91801a2_3
  intel-openmp       pkgs/main/linux-64::intel-openmp-2025.0.0-h06a4308_1172
  jansson            pkgs/main/linux-64::jansson-2.15.0-hbcba0ee_0
  libasprintf        pkgs/main/linux-64::libasprintf-0.25.1-hf2ab22a_0
  libasprintf-devel  pkgs/main/linux-64::libasprintf-devel-0.25.1-hf2ab22a_0
  libbrotlicommon    pkgs/main/linux-64::libbrotlicommon-1.2.0-h32cd6e7_0
  libbrotlidec       pkgs/main/linux-64::libbrotlidec-1.2.0-ha2c5f68_0
  libbrotlienc       pkgs/main/linux-64::libbrotlienc-1.2.0-h2e96acb_0
  libcurl            pkgs/main/linux-64::libcurl-8.21.0-hd8fa685_0
  libev              pkgs/main/linux-64::libev-4.33-h7f8727e_1
  libgettextpo       pkgs/main/linux-64::libgettextpo-0.25.1-hf2ab22a_0
  libgettextpo-devel pkgs/main/linux-64::libgettextpo-devel-0.25.1-hf2ab22a_0
  libgfortran        pkgs/main/linux-64::libgfortran-15.2.0-h166f726_8
  libgfortran5       pkgs/main/linux-64::libgfortran5-15.2.0-hc633d37_8
  libiconv           pkgs/main/linux-64::libiconv-1.18-h75a1612_0
  libidn2            pkgs/main/linux-64::libidn2-2.3.8-hf80d704_0
  libkrb5            pkgs/main/linux-64::libkrb5-1.22.2-hbd13c29_0
  libnghttp2         pkgs/main/linux-64::libnghttp2-1.69.0-hc59f8b6_0
  libssh2            pkgs/main/linux-64::libssh2-1.11.1-h251f7ec_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-15.2.0-hc03a8fd_8
  libunistring       pkgs/main/linux-64::libunistring-1.4.2-h34b0ebb_0
  lmdb               pkgs/main/linux-64::lmdb-1.0.0-hfe55579_0
  lz4-c              pkgs/main/linux-64::lz4-c-1.9.4-h7354ed3_5
  lzo                pkgs/main/linux-64::lzo-2.10-h7b6447c_2
  mkl                pkgs/main/linux-64::mkl-2025.0.0-h6d8faa4_942
  mkl-service        pkgs/main/linux-64::mkl-service-2.7.2-py311h365c7f6_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-2.2.0-py311h44c8d7b_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.4.1-py311h86c3e14_0
  numexpr            pkgs/main/linux-64::numexpr-2.14.1-py311hf74ea54_1
  numpy              pkgs/main/linux-64::numpy-2.4.6-py311h4c24699_0
  numpy-base         pkgs/main/linux-64::numpy-base-2.4.6-py311h00548fb_0
  py-cpuinfo         pkgs/main/linux-64::py-cpuinfo-9.0.0-py311h06a4308_0
  pytables           pkgs/main/linux-64::pytables-3.11.1-py311h4db2897_0
  s2n                pkgs/main/linux-64::s2n-1.6.2-h02aa81b_0
  tbb                pkgs/main/linux-64::tbb-2022.0.0-hdb19cb5_0
  tbb-devel          pkgs/main/linux-64::tbb-devel-2022.0.0-hdb19cb5_0
  zlib-ng            pkgs/main/linux-64::zlib-ng-2.0.7-h5eee18b_0
  zstd               pkgs/main/linux-64::zstd-1.5.7-h11fc155_0



Downloading and Extracting Packages:
mkl-2025.0.0         | 113.4 MB  |                                      |   0%
intel-openmp-2025.0. | 19.3 MB   |                                      |   0%

numpy-base-2.4.6     | 8.6 MB    |                                      |   0%


hdf5-2.0.0           | 7.2 MB    |                                      |   0%



pytables-3.11.1      | 1.5 MB    |                                      |   0%




libgfortran5-15.2.0  | 1.5 MB    |                                      |   0%





tbb-devel-2022.0.0   | 1.1 MB    |                                      |   0%






c-blosc2-2.22.0      | 701 KB    |                                      |   0%







lmdb-1.0.0           | 518 KB    |                                      |   0%








libcurl-8.21.0       | 501 KB    |                                      |   0%









mkl_random-1.4.1     | 393 KB    |                                      |   0%










s2n-1.6.2            | 385 KB    |                                      |   0%











aws-c-common-0.12.6  | 233 KB    |                                      |   0%












numexpr-2.14.1       | 212 KB    |                                      |   0%













aws-c-http-0.10.13   | 199 KB    |                                      |   0%














tbb-2022.0.0         | 188 KB    |                                      |   0%















lzo-2.10             | 184 KB    |                                      |   0%
















mkl_fft-2.2.0        | 182 KB    |                                      |   0%

















aws-c-io-0.26.3      | 161 KB    |                                      |   0%


















aws-c-s3-0.12.0      | 132 KB    |                                      |   0%



















aws-c-auth-0.10.1    | 118 KB    |                                      |   0%




















zlib-ng-2.0.7        | 100 KB    |                                      |   0%





















 ... (more hidden) ...

numpy-base-2.4.6     | 8.6 MB    |                                      |   0%


hdf5-2.0.0           | 7.2 MB    |                                      |   0%
intel-openmp-2025.0. | 19.3 MB   |                                      |   0%



pytables-3.11.1      | 1.5 MB    | 3                                    |   1%

numpy-base-2.4.6     | 8.6 MB    | 1                                    |   0%


mkl-2025.0.0         | 113.4 MB  |                                      |   0%



pytables-3.11.1      | 1.5 MB    | #4                                   |   4%
mkl-2025.0.0         | 113.4 MB  |                                      |   0%



pytables-3.11.1      | 1.5 MB    | ##1                                  |   6%

numpy-base-2.4.6     | 8.6 MB    | 4                                    |   1%


hdf5-2.0.0           | 7.2 MB    | 3                                    |   1%
intel-openmp-2025.0. | 19.3 MB   | 2                                    |   1%


mkl-2025.0.0         | 113.4 MB  |                                      |   0%

numpy-base-2.4.6     | 8.6 MB    | 7                                    |   2%
intel-openmp-2025.0. | 19.3 MB   | 2                                    |   1%



mkl-2025.0.0         | 113.4 MB  |                                      |   0%



pytables-3.11.1      | 1.5 MB    | ###6                                 |  10%


mkl-2025.0.0         | 113.4 MB  |                                      |   0%
intel-openmp-2025.0. | 19.3 MB   | 4                                    |   1%



pytables-3.11.1      | 1.5 MB    | ####3                                |  12%


hdf5-2.0.0           | 7.2 MB    | #6                                   |   5%

mkl-2025.0.0         | 113.4 MB  | 1                                    |   0%



pytables-3.11.1      | 1.5 MB    | #####                                |  14%
intel-openmp-2025.0. | 19.3 MB   | #2                                   |   3%

numpy-base-2.4.6     | 8.6 MB    | ##7                                  |   8%


hdf5-2.0.0           | 7.2 MB    | #8                                   |   5%
intel-openmp-2025.0. | 19.3 MB   | #6                                   |   5%


mkl-2025.0.0         | 113.4 MB  | 1                                    |   0%

numpy-base-2.4.6     | 8.6 MB    | ###3                                 |   9%


mkl-2025.0.0         | 113.4 MB  | 1                                    |   1%

numpy-base-2.4.6     | 8.6 MB    | ####7                                |  13%
intel-openmp-2025.0. | 19.3 MB   | #8                                   |   5%


hdf5-2.0.0           | 7.2 MB    | ###6                                 |  10%



pytables-3.11.1      | 1.5 MB    | #####8                               |  16%

numpy-base-2.4.6     | 8.6 MB    | #####5                               |  15%
mkl-2025.0.0         | 113.4 MB  | 2                                    |   1%
intel-openmp-2025.0. | 19.3 MB   | ###7                                 |  11%



mkl-2025.0.0         | 113.4 MB  | 2                                    |   1%

numpy-base-2.4.6     | 8.6 MB    | ######9                              |  19%


mkl-2025.0.0         | 113.4 MB  | 2                                    |   1%
intel-openmp-2025.0. | 19.3 MB   | ####4                                |  12%

numpy-base-2.4.6     | 8.6 MB    | ########8                            |  25%


hdf5-2.0.0           | 7.2 MB    | #####2                               |  14%



pytables-3.11.1      | 1.5 MB    | #########8                           |  27%


mkl-2025.0.0         | 113.4 MB  | 3                                    |   1%



pytables-3.11.1      | 1.5 MB    | ##########5                          |  29%
intel-openmp-2025.0. | 19.3 MB   | ########9                            |  25%

numpy-base-2.4.6     | 8.6 MB    | #########7                           |  27%


mkl-2025.0.0         | 113.4 MB  | 3                                    |   1%



mkl-2025.0.0         | 113.4 MB  | 4                                    |   1%


hdf5-2.0.0           | 7.2 MB    | #######                              |  20%
mkl-2025.0.0         | 113.4 MB  | 4                                    |   1%
intel-openmp-2025.0. | 19.3 MB   | ##################5                  |  51%


hdf5-2.0.0           | 7.2 MB    | ########2                            |  23%

mkl-2025.0.0         | 113.4 MB  | 4                                    |   1%

numpy-base-2.4.6     | 8.6 MB    | ################8                    |  47%


mkl-2025.0.0         | 113.4 MB  | 4                                    |   1%



mkl-2025.0.0         | 113.4 MB  | 5                                    |   2%


hdf5-2.0.0           | 7.2 MB    | ########7                            |  24%
intel-openmp-2025.0. | 19.3 MB   | ####################                 |  56%
intel-openmp-2025.0. | 19.3 MB   | #####################1               |  59%


hdf5-2.0.0           | 7.2 MB    | #########5                           |  27%
intel-openmp-2025.0. | 19.3 MB   | ######################1              |  62%



pytables-3.11.1      | 1.5 MB    | #################4                   |  48%
intel-openmp-2025.0. | 19.3 MB   | #######################2             |  65%

mkl-2025.0.0         | 113.4 MB  | 6                                    |   2%



pytables-3.11.1      | 1.5 MB    | #########################4           |  71%

numpy-base-2.4.6     | 8.6 MB    | ######################3              |  62%
mkl-2025.0.0         | 113.4 MB  | 6                                    |   2%

numpy-base-2.4.6     | 8.6 MB    | ########################1            |  67%
intel-openmp-2025.0. | 19.3 MB   | #############################5       |  82%

mkl-2025.0.0         | 113.4 MB  | 7                                    |   2%



pytables-3.11.1      | 1.5 MB    | #############################        |  81%

mkl-2025.0.0         | 113.4 MB  | 7                                    |   2%


hdf5-2.0.0           | 7.2 MB    | ##########7                          |  30%



mkl-2025.0.0         | 113.4 MB  | 8                                    |   2%
intel-openmp-2025.0. | 19.3 MB   | ##############################9      |  86%


hdf5-2.0.0           | 7.2 MB    | ###########9                         |  33%
intel-openmp-2025.0. | 19.3 MB   | ###############################9     |  89%

numpy-base-2.4.6     | 8.6 MB    | ############################9        |  80%



pytables-3.11.1      | 1.5 MB    | ##################################4  |  96%



pytables-3.11.1      | 1.5 MB    | #################################### | 100%


hdf5-2.0.0           | 7.2 MB    | ############2                        |  34%

numpy-base-2.4.6     | 8.6 MB    | ###############################2     |  87%



mkl-2025.0.0         | 113.4 MB  | 8                                    |   2%
intel-openmp-2025.0. | 19.3 MB   | ################################8    |  91%

mkl-2025.0.0         | 113.4 MB  | 8                                    |   2%
intel-openmp-2025.0. | 19.3 MB   | ##################################   |  95%




libgfortran5-15.2.0  | 1.5 MB    | 3                                    |   1%
intel-openmp-2025.0. | 19.3 MB   | #################################### | 100%

numpy-base-2.4.6     | 8.6 MB    | ###################################9 | 100%

numpy-base-2.4.6     | 8.6 MB    | #################################### | 100%




libgfortran5-15.2.0  | 1.5 MB    | ##2                                  |   6%





mkl-2025.0.0         | 113.4 MB  | 9                                    |   3%




libgfortran5-15.2.0  | 1.5 MB    | ###3                                 |   9%


mkl-2025.0.0         | 113.4 MB  | 9                                    |   3%






c-blosc2-2.22.0      | 701 KB    | 8                                    |   2%


hdf5-2.0.0           | 7.2 MB    | #############3                       |  37%
intel-openmp-2025.0. | 19.3 MB   | #################################### | 100%
intel-openmp-2025.0. | 19.3 MB   | #################################### | 100%




libgfortran5-15.2.0  | 1.5 MB    | ####4                                |  12%




libgfortran5-15.2.0  | 1.5 MB    | #####6                               |  16%





mkl-2025.0.0         | 113.4 MB  | #                                    |   3%

numpy-base-2.4.6     | 8.6 MB    | #################################### | 100%


hdf5-2.0.0           | 7.2 MB    | #############7                       |  38%






mkl-2025.0.0         | 113.4 MB  | #                                    |   3%





tbb-devel-2022.0.0   | 1.1 MB    | ########6                            |  24%




libgfortran5-15.2.0  | 1.5 MB    | ######7                              |  19%


hdf5-2.0.0           | 7.2 MB    | ##############                       |  39%






c-blosc2-2.22.0      | 701 KB    | #####7                               |  16%




libgfortran5-15.2.0  | 1.5 MB    | #######8                             |  22%






mkl-2025.0.0         | 113.4 MB  | #                                    |   3%






c-blosc2-2.22.0      | 701 KB    | ############################7        |  80%






c-blosc2-2.22.0      | 701 KB    | #################################### | 100%





tbb-devel-2022.0.0   | 1.1 MB    | ####################9                |  58%





tbb-devel-2022.0.0   | 1.1 MB    | #################################### | 100%






c-blosc2-2.22.0      | 701 KB    | #################################### | 100%


hdf5-2.0.0           | 7.2 MB    | ##############3                      |  40%




libgfortran5-15.2.0  | 1.5 MB    | ###########2                         |  31%





tbb-devel-2022.0.0   | 1.1 MB    | #################################### | 100%





mkl-2025.0.0         | 113.4 MB  | #1                                   |   3%




libgfortran5-15.2.0  | 1.5 MB    | ##############5                      |  40%








mkl-2025.0.0         | 113.4 MB  | #1                                   |   3%




mkl-2025.0.0         | 113.4 MB  | #1                                   |   3%







lmdb-1.0.0           | 518 KB    | #1                                   |   3%


hdf5-2.0.0           | 7.2 MB    | ##############9                      |  42%







lmdb-1.0.0           | 518 KB    | ###############5                     |  43%







lmdb-1.0.0           | 518 KB    | ###########################7         |  77%




mkl-2025.0.0         | 113.4 MB  | #2                                   |   3%








libcurl-8.21.0       | 501 KB    | ##2                                  |   6%








libcurl-8.21.0       | 501 KB    | ##############9                      |  41%




mkl-2025.0.0         | 113.4 MB  | #2                                   |   3%








libcurl-8.21.0       | 501 KB    | ######################9              |  64%








libcurl-8.21.0       | 501 KB    | #################################### | 100%








mkl-2025.0.0         | 113.4 MB  | #2                                   |   3%


hdf5-2.0.0           | 7.2 MB    | ###############4                     |  43%


hdf5-2.0.0           | 7.2 MB    | ################                     |  45%




mkl-2025.0.0         | 113.4 MB  | #2                                   |   4%




mkl-2025.0.0         | 113.4 MB  | #2                                   |   4%


mkl-2025.0.0         | 113.4 MB  | #2                                   |   4%









mkl_random-1.4.1     | 393 KB    | #4                                   |   4%




mkl-2025.0.0         | 113.4 MB  | #3                                   |   4%



In [17]:
frame = pd.DataFrame({'a': np.random.standard_normal(100)})

In [18]:
store = pd.HDFStore('pydata-book/examples/mydata.h5')

In [19]:
store['obj1'] = frame

In [22]:
store['obj1_col'] = frame['a']

In [23]:
store

<class 'pandas.HDFStore'>
File path: pydata-book/examples/mydata.h5

In [24]:
store['obj1']

           a
0  -0.157475
1  -0.805344
2  -0.154750
3   1.912395
4   0.652868
..       ...
95 -0.407269
96  0.264975
97  1.294464
98  1.086917
99 -1.204093

[100 rows x 1 columns]

In [25]:
store.put('obj2', frame, format='table')

In [26]:
store.select('obj2', where=['index >= 10 and index <= 15'])

           a
10  0.166226
11  0.941367
12  0.927991
13  0.864028
14  1.220389
15 -0.564858

In [27]:
store.close

<bound method HDFStore.close of <class 'pandas.HDFStore'>
File path: pydata-book/examples/mydata.h5
>

In [28]:
frame.to_hdf('pydata-book/examples/mydata.h5', 'obj3', format='table')

TypeError: NDFrame.to_hdf() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

In [29]:
pd.read_hdf('pydata-book/examples/mydata.h5', 'obj3', where=['index < 5'])

ValueError: The file 'pydata-book/examples/mydata.h5' is already opened, but not in read-only mode (as requested).

In [30]:
import os

In [31]:
os.remove('pydata-book/examples/mydata.h5')