# Summary and Calculation of Descriptive Statistics

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                   index=['a', 'b', 'c', 'd'],
                   columns=['one', 'two'])

In [4]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [5]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [6]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [7]:
df.sum(axis='index', skipna=False)

one   NaN
two   NaN
dtype: float64

In [8]:
df.sum(axis='columns', skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [9]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [11]:
df.idxmax()

one    b
two    d
dtype: str

In [12]:
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [13]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [14]:
obj = pd.Series(['a', 'a', 'b' , 'c'] * 4)

In [15]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## 1.Correlation Coefficient and Covariance

In [18]:
price = pd.read_pickle('pydata-book/examples/yahoo_price.pkl')

FileNotFoundError: [Errno 2] No such file or directory: 'pydata-book/examples/yahoo_price.pkl'