# Base Functions of Series and DataFrame

## 1.Rebuild Index

In [1]:
import pandas as pd
import numpy as np

In [2]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c']) # create a pandas Series with specified index

In [3]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [4]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) # reindex the Series to a new index, introducing NaN for missing values

In [5]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [6]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4]) # create a new Series with non-consecutive indices

In [7]:
obj3

0      blue
2    purple
4    yellow
dtype: str

In [9]:
obj3.reindex(np.arange(6), method='ffill') # reindex the Series to a new index range, using forword fill methon to fill missing values

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

In [10]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California']) # create a DataFrame with specified index and columns

In [11]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [14]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd']) # reindex the DataFrame to a new index, introducing NaN for missing values

In [16]:
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [17]:
states = ['Texas', 'Utah', 'California'] # create a list of states

In [18]:
frame.reindex(columns=states) # reindex the DataFrame to a new column order, introducing NaN for missing values

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [19]:
frame.reindex(states, axis='columns') # reindex the DataFrame to a new column order using axis parameter, introducing NaN for missing values

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [20]:
frame.loc[['a', 'd', 'c'], ['California', 'Texas']] # select specific rows and columns from the DataFrame using .loc

   California  Texas
a           2      1
d           8      7
c           5      4

## Drop items on the specified axis